### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by NicoCG** [fablecode/ygo-api#1]
Hello,

Could you kindly publish a web interface like the example below?

https://github.com/EduardoPires/EquinoxProject/tree/master/src/Equinox.UI.Site

Or could you show me of an example someone has done.

**Comment by fablecode** [comment]
There's no web interface this api, except [SwaggerUI](http://www.ygo-api.com/swagger/index.html) for documentation.

For example usage, i've created [Dueltank](https://www.dueltank.com) and the repo is publicly available.
